package tr.com.mernis.client;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "KPSPublicSoap", targetNamespace = "http://tckimlik.nvi.gov.tr/WS")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface KPSPublicSoap {


    /**
     * @param dogumYili
     * @param ad
     * @param tcKimlikNo
     * @param soyad
     * @return returns boolean
     */
    @WebMethod(operationName = "TCKimlikNoDogrula", action = "http://tckimlik.nvi.gov.tr/WS/TCKimlikNoDogrula")
    @WebResult(name = "TCKimlikNoDogrulaResult", targetNamespace = "http://tckimlik.nvi.gov.tr/WS")
    @RequestWrapper(localName = "TCKimlikNoDogrula", targetNamespace = "http://tckimlik.nvi.gov.tr/WS", className = "tr.com.mernis.client.TCKimlikNoDogrula")
    @ResponseWrapper(localName = "TCKimlikNoDogrulaResponse", targetNamespace = "http://tckimlik.nvi.gov.tr/WS", className = "tr.com.mernis.client.TCKimlikNoDogrulaResponse")
    public boolean tcKimlikNoDogrula(
            @WebParam(name = "TCKimlikNo", targetNamespace = "http://tckimlik.nvi.gov.tr/WS")
            long tcKimlikNo,
            @WebParam(name = "Ad", targetNamespace = "http://tckimlik.nvi.gov.tr/WS")
            String ad,
            @WebParam(name = "Soyad", targetNamespace = "http://tckimlik.nvi.gov.tr/WS")
            String soyad,
            @WebParam(name = "DogumYili", targetNamespace = "http://tckimlik.nvi.gov.tr/WS")
            int dogumYili);

}
